---
title: "Progress Memo 2"
subtitle: |
  | Final Project 
  | Data Science 1 with R (STAT 301-1)
author: "Chelsea Nelson"
date: today
format:
  html:
    
    toc: true
    embed-resources: true
execute:
  echo: false
  warning: false
from: markdown+emoji 
editor: 
  markdown: 
    wrap: 72
---

::: {.callout-tip icon="false"}
## Github Repo Link

[Final Project 1
Repo](https://github.com/stat301-1-2023-fall/final-project-1-chelseanelson)
:::

```{r}
#| label: loading_packages_and_datsets

# loading packages
library(tidyverse)
library(readxl)

# loading datasets
# larger version of dataset
fbc_data <- read_excel("data/raw/fbc_data_2022.xlsx", sheet = "County") %>% 
  janitor::clean_names()
fbc_data_codebook <- read_excel("data/raw/fbc_data_2022.xlsx", 
                                sheet = "Codebook")

# smaller version of dataset --> only shows annual cost
cost_of_living_us <- read_csv("data/raw/cost_of_living_us.csv") 

```

# Progress Summary

## Data Wrangling

```{r}
#| label: data_wrangling 

# adding minimum wage
fbc_data <- fbc_data %>% mutate(
  minimum_wage = case_when(
    state_abv %in% c("AL","GA","ID","IN","IA",
                     "KS","KY","LA","MS","NH","NC","ND",
                     "OK","PA","SC","TN", "TX","UT","WI","WY") ~ 7.25,
    state_abv %in% c("AR","FL","VA") ~ 11.00,
    state_abv == "AK" ~ 10.34,
    state_abv == "AZ" ~ 12.80,
    state_abv == "CA" ~ 15.00,
    state_abv == "CO" ~ 12.56,
    state_abv == "CT" ~ 14.00,
    state_abv %in% c("DE","NV") ~ 10.50,
    state_abv %in% c("HI","IL") ~ 12.00,
    state_abv == "ME" ~ 12.75,
    state_abv == "MD" ~ 12.50,
    state_abv == "MA" ~ 14.25,
    state_abv == "MI" ~ 9.87,
    state_abv == "MN" ~ 10.33,
    state_abv == "MO" ~ 11.15,
    state_abv == "MT" ~ 9.20,
    state_abv == "NE" ~ 9.00,
    state_abv == "NJ" ~ 13.00,
    state_abv == "NM" ~ 11.50, 
    # there is a different minimum wage for jobs in New York City,
    # Long Island, and Westchester
    state_abv == "NY" & county %in% 
      c("Westchester County", "New York County", 
        "Kings County", "Queens County", "Bronx County", 
        "Richmond County", "Nassau County", "Suffolk County") ~ 15.00,
    state_abv == "NY" ~ 13.20,
    state_abv == "OH" ~ 9.30,
    state_abv == "OR" & metro == 0 ~ 12.50,
    state_abv == "OR" & county %in% c("Multnomah County", "Washington County",
                                      "Clackamas County") ~ 14.75,
    state_abv == "OR" ~ 13.50,
    state_abv == "RI" ~ 12.25,
    state_abv == "SD" ~ 9.95,
    state_abv == "VT" ~ 12.55,
    state_abv == "WA" ~ 14.49,
    state_abv == "WV" ~ 8.75
    )
)

fbc_data %>% 
  relocate(minimum_wage) %>% slice_sample(n = 10) %>%
 knitr::kable()

# adding racial majority of county 



```

```{r}
#| label: testing_code
#| results: hide

fbc_data %>% 
  relocate(minimum_wage) %>% 
  filter(state_abv == "OR" & county == "Washington County")

fbc_data %>% 
  relocate(minimum_wage) %>% 
  filter(state_abv == "TX")

fbc_data %>% 
  relocate(minimum_wage) %>% 
  filter(state_abv == "NY" & 
           county %in% c("New York County", "Albany County"))
```


State what I did in my code here 

## Current EDA

# Next Steps

I plan to make a codebook for my dataset within RStudio, rather than 
making it in excel and then importing it into RStudio.

## Research To Explore
